import { User } from '../types/auth';
import { College } from '../types/college';
import { Student } from '../types/student';
import { Listing } from '../types/listing';
import { Transaction } from '../types/transaction';
import { Report } from '../types/report';
import { EnvironmentalImpactSummary, ImpactByDepartment } from '../types/impact';
import { KpiMetric, MonthlyCirculation, CategoryMetric, CollegeLeaderboardItem } from '../types/analytics';

export const MOCK_SUPER_ADMIN: User = {
  id: 'usr_super_01',
  name: 'Aarav Sharma',
  email: 'superadmin@campusloop.in',
  role: 'SUPER_ADMIN',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  createdAt: '2025-01-10T10:00:00Z',
};

export const MOCK_COLLEGE_ADMIN: User = {
  id: 'usr_col_admin_01',
  name: 'Dr. Meera Nambiar',
  email: 'admin@iitb.ac.in',
  role: 'COLLEGE_ADMIN',
  collegeId: 'col_01',
  collegeName: 'IIT Bombay',
  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  createdAt: '2025-02-15T09:30:00Z',
};

export const MOCK_COLLEGES: College[] = [
  {
    id: 'col_01',
    name: 'Indian Institute of Technology Bombay',
    code: 'IITB',
    domain: 'iitb.ac.in',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    logo: 'https://images.unsplash.com/photo-1562774053-701939374585?w=120&auto=format&fit=crop&q=80',
    contactEmail: 'campusloop@iitb.ac.in',
    contactPhone: '+91 22 2576 4000',
    adminName: 'Dr. Meera Nambiar',
    status: 'ACTIVE',
    studentCount: 4210,
    listingCount: 840,
    circularityScore: 94,
    onboardedAt: '2025-01-15T00:00:00Z',
    pickupHubs: ['Central Library Desk A', 'Hostel 14 Common Room', 'SAC Helpdesk'],
  },
  {
    id: 'col_02',
    name: 'Birla Institute of Technology & Science, Pilani',
    code: 'BITS',
    domain: 'bits-pilani.ac.in',
    city: 'Pilani',
    state: 'Rajasthan',
    country: 'India',
    logo: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=120&auto=format&fit=crop&q=80',
    contactEmail: 'sustainability@pilani.bits-pilani.ac.in',
    contactPhone: '+91 1596 245 073',
    adminName: 'Prof. Rajesh Kulkarni',
    status: 'ACTIVE',
    studentCount: 3680,
    listingCount: 620,
    circularityScore: 88,
    onboardedAt: '2025-02-01T00:00:00Z',
    pickupHubs: ['Student Activity Center', 'Library Ground Floor', 'Krishna Bhawan Hub'],
  },
  {
    id: 'col_03',
    name: 'Delhi Technological University',
    code: 'DTU',
    domain: 'dtu.ac.in',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    logo: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=120&auto=format&fit=crop&q=80',
    contactEmail: 'admin@dtu.ac.in',
    contactPhone: '+91 11 2787 1018',
    adminName: 'Dr. Ananya Verma',
    status: 'ACTIVE',
    studentCount: 2950,
    listingCount: 410,
    circularityScore: 82,
    onboardedAt: '2025-02-20T00:00:00Z',
    pickupHubs: ['OAT Canteen Loop Corner', 'Mech Block Ground Floor'],
  },
  {
    id: 'col_04',
    name: 'National Institute of Technology Karnataka',
    code: 'NITK',
    domain: 'nitk.edu.in',
    city: 'Surathkal',
    state: 'Karnataka',
    country: 'India',
    logo: 'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=120&auto=format&fit=crop&q=80',
    contactEmail: 'loop@nitk.edu.in',
    contactPhone: '+91 824 247 4000',
    adminName: 'Suresh Hegde',
    status: 'ACTIVE',
    studentCount: 2430,
    listingCount: 315,
    circularityScore: 79,
    onboardedAt: '2025-03-01T00:00:00Z',
    pickupHubs: ['Main Building Portico', 'Mega Tower 1 Handoff Desk'],
  },
  {
    id: 'col_05',
    name: 'Manipal Academy of Higher Education',
    code: 'MAHE',
    domain: 'manipal.edu',
    city: 'Manipal',
    state: 'Karnataka',
    country: 'India',
    logo: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=120&auto=format&fit=crop&q=80',
    contactEmail: 'ecoloop@manipal.edu',
    contactPhone: '+91 922 633 5000',
    adminName: 'Tanvi Deshmukh',
    status: 'PENDING_APPROVAL',
    studentCount: 1820,
    listingCount: 140,
    circularityScore: 71,
    onboardedAt: '2026-08-10T00:00:00Z',
    pickupHubs: ['MIT Student Center', 'KMC Library'],
  }
];

export const MOCK_STUDENTS: Student[] = [
  {
    id: 'std_01',
    fullName: 'Rohan Gupta',
    email: 'rohan.gupta@iitb.ac.in',
    rollNumber: '22B030042',
    collegeId: 'col_01',
    collegeName: 'IIT Bombay',
    department: 'Computer Science & Engineering',
    graduationYear: 2026,
    idCardUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=400&auto=format&fit=crop&q=80',
    trustScore: 98,
    strikes: 0,
    status: 'VERIFIED',
    joinedAt: '2025-01-20T11:20:00Z',
    itemsShared: 14,
    itemsBorrowed: 8,
    co2SavedKg: 42.5,
    phone: '+91 98765 43210',
  },
  {
    id: 'std_02',
    fullName: 'Priya Sundaram',
    email: 'priya.s@iitb.ac.in',
    rollNumber: '23M010018',
    collegeId: 'col_01',
    collegeName: 'IIT Bombay',
    department: 'Mechanical Engineering',
    graduationYear: 2027,
    idCardUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    trustScore: 92,
    strikes: 0,
    status: 'VERIFIED',
    joinedAt: '2025-02-05T14:45:00Z',
    itemsShared: 9,
    itemsBorrowed: 12,
    co2SavedKg: 31.0,
    phone: '+91 98123 45678',
  },
  {
    id: 'std_03',
    fullName: 'Aditya Vardhan',
    email: 'aditya.v@bits-pilani.ac.in',
    rollNumber: '2022A7PS0145P',
    collegeId: 'col_02',
    collegeName: 'BITS Pilani',
    department: 'Electrical & Electronics',
    graduationYear: 2026,
    idCardUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    trustScore: 88,
    strikes: 0,
    status: 'VERIFIED',
    joinedAt: '2025-02-12T09:15:00Z',
    itemsShared: 6,
    itemsBorrowed: 5,
    co2SavedKg: 22.8,
    phone: '+91 97654 32109',
  },
  {
    id: 'std_04',
    fullName: 'Sneha Chawla',
    email: 'sneha.c@dtu.ac.in',
    rollNumber: '2K23/SE/102',
    collegeId: 'col_03',
    collegeName: 'DTU',
    department: 'Software Engineering',
    graduationYear: 2027,
    idCardUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    trustScore: 80,
    strikes: 0,
    status: 'PENDING',
    joinedAt: '2026-08-28T16:00:00Z',
    itemsShared: 0,
    itemsBorrowed: 0,
    co2SavedKg: 0,
    phone: '+91 99887 76655',
  },
  {
    id: 'std_05',
    fullName: 'Kunal Singhania',
    email: 'kunal.singh@iitb.ac.in',
    rollNumber: '21B040019',
    collegeId: 'col_01',
    collegeName: 'IIT Bombay',
    department: 'Civil Engineering',
    graduationYear: 2025,
    idCardUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    trustScore: 45,
    strikes: 2,
    status: 'SUSPENDED',
    joinedAt: '2025-01-25T13:30:00Z',
    itemsShared: 3,
    itemsBorrowed: 7,
    co2SavedKg: 11.2,
    phone: '+91 91234 56789',
  },
  {
    id: 'std_06',
    fullName: 'Varun Bhattacharya',
    email: 'varun.b@nitk.edu.in',
    rollNumber: '221IT054',
    collegeId: 'col_04',
    collegeName: 'NITK',
    department: 'Information Technology',
    graduationYear: 2026,
    idCardUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80',
    trustScore: 95,
    strikes: 0,
    status: 'VERIFIED',
    joinedAt: '2025-03-05T10:10:00Z',
    itemsShared: 8,
    itemsBorrowed: 3,
    co2SavedKg: 28.4,
    phone: '+91 94455 66778',
  }
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'lst_01',
    title: 'Introduction to Algorithms (CLRS) 4th Edition',
    description: 'Original MIT Press paperback edition. Clean pages with minimal pencil highlights. Ideal for Data Structures and Algorithms semester course.',
    category: 'TEXTBOOKS',
    condition: 'LIKE_NEW',
    type: 'BORROW_RENT',
    price: 150, // ₹150 for entire semester
    depositAmount: 500,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&auto=format&fit=crop&q=80'],
    studentId: 'std_01',
    studentName: 'Rohan Gupta',
    studentEmail: 'rohan.gupta@iitb.ac.in',
    collegeId: 'col_01',
    collegeName: 'IIT Bombay',
    status: 'ACTIVE',
    viewCount: 142,
    timesShared: 3,
    pickupLocation: 'Central Library Desk A',
    createdAt: '2026-08-15T10:30:00Z',
    updatedAt: '2026-08-15T10:30:00Z',
  },
  {
    id: 'lst_02',
    title: 'Casio FX-991EX Classwiz Scientific Calculator',
    description: 'High-speed spreadsheet and equation solver. Solar powered with pristine display. Approved for mid-sem and end-sem exams.',
    category: 'ELECTRONICS',
    condition: 'LIKE_NEW',
    type: 'BORROW_RENT',
    price: 80,
    depositAmount: 600,
    images: ['https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=500&auto=format&fit=crop&q=80'],
    studentId: 'std_02',
    studentName: 'Priya Sundaram',
    studentEmail: 'priya.s@iitb.ac.in',
    collegeId: 'col_01',
    collegeName: 'IIT Bombay',
    status: 'ACTIVE',
    viewCount: 210,
    timesShared: 5,
    pickupLocation: 'Hostel 14 Common Room',
    createdAt: '2026-08-18T14:10:00Z',
    updatedAt: '2026-08-18T14:10:00Z',
  },
  {
    id: 'lst_03',
    title: 'Firefox Grunge 26T Mountain Bike (Geared)',
    description: 'Dual disc brakes, Shimano 21 gears, front suspension. Serviced last month. Great for commuting between hostels and academic blocks.',
    category: 'BICYCLES_MOBILITY',
    condition: 'GOOD',
    type: 'BORROW_RENT',
    price: 450,
    depositAmount: 1500,
    images: ['https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=500&auto=format&fit=crop&q=80'],
    studentId: 'std_03',
    studentName: 'Aditya Vardhan',
    studentEmail: 'aditya.v@bits-pilani.ac.in',
    collegeId: 'col_02',
    collegeName: 'BITS Pilani',
    status: 'ACTIVE',
    viewCount: 380,
    timesShared: 4,
    pickupLocation: 'Krishna Bhawan Hub',
    createdAt: '2026-08-20T08:00:00Z',
    updatedAt: '2026-08-20T08:00:00Z',
  },
  {
    id: 'lst_04',
    title: 'Engineering Drawing Board + Mini Drafter Kit',
    description: 'Standard A2 size imperial wooden drawing board with Omega mini drafter, T-scale, set squares and drafting clips.',
    category: 'LAB_EQUIPMENT',
    condition: 'GOOD',
    type: 'FREE_GIVEAWAY',
    price: 0,
    depositAmount: 0,
    images: ['https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=500&auto=format&fit=crop&q=80'],
    studentId: 'std_01',
    studentName: 'Rohan Gupta',
    studentEmail: 'rohan.gupta@iitb.ac.in',
    collegeId: 'col_01',
    collegeName: 'IIT Bombay',
    status: 'ACTIVE',
    viewCount: 165,
    timesShared: 2,
    pickupLocation: 'Central Library Desk A',
    createdAt: '2026-08-22T12:00:00Z',
    updatedAt: '2026-08-22T12:00:00Z',
  },
  {
    id: 'lst_05',
    title: 'Godrej 45L Compact Dorm Mini Refrigerator',
    description: 'Perfect for hostel room. Chills water bottles, milk cartons, fruits. Whisper-quiet compressor with A+ energy efficiency.',
    category: 'DORM_LIVING',
    condition: 'LIKE_NEW',
    type: 'SELL_FAIR_PRICE',
    price: 3200,
    depositAmount: 0,
    images: ['https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=500&auto=format&fit=crop&q=80'],
    studentId: 'std_05',
    studentName: 'Kunal Singhania',
    studentEmail: 'kunal.singh@iitb.ac.in',
    collegeId: 'col_01',
    collegeName: 'IIT Bombay',
    status: 'FLAGGED',
    flagReason: 'Seller requested payment outside platform escrow and disputed pickup condition',
    viewCount: 490,
    timesShared: 1,
    pickupLocation: 'Hostel 14 Common Room',
    createdAt: '2026-08-10T15:20:00Z',
    updatedAt: '2026-08-25T11:00:00Z',
  },
  {
    id: 'lst_06',
    title: 'Arduino Mega 2560 Starter Kit with 30 Sensors',
    description: 'Original ATmega2560 board with jumper cables, ultrasonic sensors, relay modules, LCD screen and breadboard for robotics projects.',
    category: 'ELECTRONICS',
    condition: 'NEW',
    type: 'BORROW_RENT',
    price: 200,
    depositAmount: 1000,
    images: ['https://images.unsplash.com/photo-1553406830-ef2513450d76?w=500&auto=format&fit=crop&q=80'],
    studentId: 'std_06',
    studentName: 'Varun Bhattacharya',
    studentEmail: 'varun.b@nitk.edu.in',
    collegeId: 'col_04',
    collegeName: 'NITK',
    status: 'PENDING_REVIEW',
    viewCount: 75,
    timesShared: 0,
    pickupLocation: 'Main Building Portico',
    createdAt: '2026-09-01T17:40:00Z',
    updatedAt: '2026-09-01T17:40:00Z',
  }
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_01',
    listingId: 'lst_01',
    listingTitle: 'Introduction to Algorithms (CLRS) 4th Edition',
    listingCategory: 'TEXTBOOKS',
    ownerId: 'std_01',
    ownerName: 'Rohan Gupta',
    borrowerId: 'std_02',
    borrowerName: 'Priya Sundaram',
    collegeId: 'col_01',
    collegeName: 'IIT Bombay',
    pickupHub: 'Central Library Desk A',
    rentalDurationDays: 90,
    depositHeld: 500,
    totalFee: 150,
    status: 'ACTIVE',
    startDate: '2026-08-16T11:00:00Z',
    dueDate: '2026-11-16T18:00:00Z',
    createdAt: '2026-08-15T15:30:00Z',
  },
  {
    id: 'tx_02',
    listingId: 'lst_02',
    listingTitle: 'Casio FX-991EX Classwiz Scientific Calculator',
    listingCategory: 'ELECTRONICS',
    ownerId: 'std_02',
    ownerName: 'Priya Sundaram',
    borrowerId: 'std_04',
    borrowerName: 'Sneha Chawla',
    collegeId: 'col_01',
    collegeName: 'IIT Bombay',
    pickupHub: 'Hostel 14 Common Room',
    rentalDurationDays: 14,
    depositHeld: 600,
    totalFee: 80,
    status: 'RETURNED',
    startDate: '2026-08-19T09:00:00Z',
    dueDate: '2026-09-02T18:00:00Z',
    returnDate: '2026-09-02T16:30:00Z',
    createdAt: '2026-08-18T18:00:00Z',
  },
  {
    id: 'tx_03',
    listingId: 'lst_03',
    listingTitle: 'Firefox Grunge 26T Mountain Bike (Geared)',
    listingCategory: 'BICYCLES_MOBILITY',
    ownerId: 'std_03',
    ownerName: 'Aditya Vardhan',
    borrowerId: 'std_06',
    borrowerName: 'Varun Bhattacharya',
    collegeId: 'col_02',
    collegeName: 'BITS Pilani',
    pickupHub: 'Krishna Bhawan Hub',
    rentalDurationDays: 30,
    depositHeld: 1500,
    totalFee: 450,
    status: 'PICKED_UP',
    startDate: '2026-08-25T16:00:00Z',
    dueDate: '2026-09-25T18:00:00Z',
    createdAt: '2026-08-24T12:00:00Z',
  },
  {
    id: 'tx_04',
    listingId: 'lst_05',
    listingTitle: 'Godrej 45L Compact Dorm Mini Refrigerator',
    listingCategory: 'DORM_LIVING',
    ownerId: 'std_05',
    ownerName: 'Kunal Singhania',
    borrowerId: 'std_01',
    borrowerName: 'Rohan Gupta',
    collegeId: 'col_01',
    collegeName: 'IIT Bombay',
    pickupHub: 'Hostel 14 Common Room',
    depositHeld: 3200,
    totalFee: 3200,
    status: 'DISPUTED',
    disputeReason: 'Buyer reports cooling coil defective upon inspection at campus hub; seller refusing escrow cancellation.',
    startDate: '2026-08-26T14:00:00Z',
    createdAt: '2026-08-25T10:00:00Z',
  }
];

export const MOCK_REPORTS: Report[] = [
  {
    id: 'rep_01',
    targetType: 'TRANSACTION',
    targetId: 'tx_04',
    targetTitle: 'Godrej 45L Compact Dorm Mini Refrigerator',
    reportedById: 'std_01',
    reportedByName: 'Rohan Gupta',
    accusedId: 'std_05',
    accusedName: 'Kunal Singhania',
    collegeId: 'col_01',
    collegeName: 'IIT Bombay',
    reason: 'DAMAGED_ITEM',
    priority: 'HIGH',
    description: 'Item was listed as "Like New" but compressor fails to start. Seller claimed it worked before handoff and demanded cash release outside the app escrow.',
    evidenceUrls: ['https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=400&auto=format&fit=crop&q=80'],
    status: 'OPEN',
    createdAt: '2026-08-26T16:00:00Z',
  },
  {
    id: 'rep_02',
    targetType: 'LISTING',
    targetId: 'lst_05',
    targetTitle: 'Prohibited commercial textbook resale',
    reportedById: 'std_02',
    reportedByName: 'Priya Sundaram',
    accusedId: 'std_05',
    accusedName: 'Kunal Singhania',
    collegeId: 'col_01',
    collegeName: 'IIT Bombay',
    reason: 'PROHIBITED_ITEM',
    priority: 'MEDIUM',
    description: 'User repeatedly posting photocopied copyrighted course booklets for commercial profit against campus guidelines.',
    status: 'UNDER_INVESTIGATION',
    createdAt: '2026-08-27T09:30:00Z',
  },
  {
    id: 'rep_03',
    targetType: 'STUDENT',
    targetId: 'std_05',
    targetTitle: 'Late return and unresponsiveness',
    reportedById: 'std_03',
    reportedByName: 'Aditya Vardhan',
    accusedId: 'std_05',
    accusedName: 'Kunal Singhania',
    collegeId: 'col_01',
    collegeName: 'IIT Bombay',
    reason: 'LATE_RETURN',
    priority: 'MEDIUM',
    description: 'Kept scientific calculator 10 days past deadline and did not reply on CampusLoop chat.',
    status: 'RESOLVED',
    resolutionNote: 'User penalized with 1 strike and late fee deducted from security deposit.',
    resolvedAt: '2026-08-29T11:00:00Z',
    resolvedBy: 'Dr. Meera Nambiar',
    createdAt: '2026-08-28T14:15:00Z',
  }
];

export const MOCK_IMPACT_SUMMARY: EnvironmentalImpactSummary = {
  totalKgCo2Saved: 14820,
  totalKgWasteDiverted: 6430,
  totalINRStudentSavings: 1845000,
  totalItemsRecirculated: 2320,
  equivalentTreesPlanted: 710,
  waterSavedLiters: 184000,
  averageCirculationPerItem: 3.6,
};

export const MOCK_IMPACT_DEPARTMENTS: ImpactByDepartment[] = [
  { department: 'Computer Science', itemsShared: 740, co2SavedKg: 4920, wasteDivertedKg: 2100 },
  { department: 'Mechanical Eng.', itemsShared: 580, co2SavedKg: 4100, wasteDivertedKg: 1950 },
  { department: 'Electrical Eng.', itemsShared: 490, co2SavedKg: 3200, wasteDivertedKg: 1320 },
  { department: 'Civil Eng.', itemsShared: 290, co2SavedKg: 1600, wasteDivertedKg: 640 },
  { department: 'Design & Architecture', itemsShared: 220, co2SavedKg: 1000, wasteDivertedKg: 420 },
];

export const MOCK_LEADERBOARD: CollegeLeaderboardItem[] = [
  { rank: 1, collegeId: 'col_01', collegeName: 'IIT Bombay', exchangesCount: 840, wasteDivertedKg: 2480, co2SavedKg: 5820, studentSavingsINR: 710000 },
  { rank: 2, collegeId: 'col_02', collegeName: 'BITS Pilani', exchangesCount: 620, wasteDivertedKg: 1810, co2SavedKg: 4230, studentSavingsINR: 520000 },
  { rank: 3, collegeId: 'col_03', collegeName: 'DTU New Delhi', exchangesCount: 410, wasteDivertedKg: 1140, co2SavedKg: 2790, studentSavingsINR: 345000 },
  { rank: 4, collegeId: 'col_04', collegeName: 'NITK Surathkal', exchangesCount: 315, wasteDivertedKg: 780, co2SavedKg: 1980, studentSavingsINR: 270000 },
];

export const MOCK_DASHBOARD_KPIS: KpiMetric[] = [
  { id: 'kpi_1', label: 'Items Recirculated', value: '2,320', changePercent: 18.4, isPositive: true, sublabel: 'vs. last month' },
  { id: 'kpi_2', label: 'Active Campus Exchanges', value: '184', changePercent: 12.1, isPositive: true, sublabel: 'live peer handoffs' },
  { id: 'kpi_3', label: 'CO₂ Prevented', value: '14,820 kg', changePercent: 24.6, isPositive: true, sublabel: 'circular footprint' },
  { id: 'kpi_4', label: 'Student Savings', value: '₹18.45 Lakhs', changePercent: 15.3, isPositive: true, sublabel: 'retained by students' },
];

export const MOCK_MONTHLY_DATA: MonthlyCirculation[] = [
  { month: 'Apr', exchanges: 120, newUsers: 140, co2SavedKg: 850 },
  { month: 'May', exchanges: 190, newUsers: 220, co2SavedKg: 1300 },
  { month: 'Jun', exchanges: 260, newUsers: 310, co2SavedKg: 1750 },
  { month: 'Jul', exchanges: 420, newUsers: 590, co2SavedKg: 2900 }, // Start of semester surge
  { month: 'Aug', exchanges: 680, newUsers: 840, co2SavedKg: 4600 },
  { month: 'Sep', exchanges: 650, newUsers: 720, co2SavedKg: 4420 },
];

export const MOCK_CATEGORY_METRICS: CategoryMetric[] = [
  { category: 'Textbooks & Notes', count: 860, percentage: 37, color: '#3b82f6' },
  { category: 'Calculators & Electronics', count: 520, percentage: 22, color: '#6366f1' },
  { category: 'Cycles & Mobility', count: 390, percentage: 17, color: '#10b981' },
  { category: 'Dorm & Living Essentials', count: 310, percentage: 13, color: '#f59e0b' },
  { category: 'Lab Equipment & Tools', count: 240, percentage: 11, color: '#14b8a6' },
];
