import React, { useState, useEffect } from 'react';
import {
  Leaf,
  TreeDeciduous,
  Droplets,
  Trash2,
  DollarSign,
  Award,
  Download,
  CheckCircle2,
  Sparkles,
} from 'lucide-react';
import { useAuth } from '../../hooks/useAuth';
import { useToast } from '../../hooks/useToast';
import { impactService } from '../../services/impactService';
import { analyticsService } from '../../services/analyticsService';
import { EnvironmentalImpactSummary, ImpactByDepartment } from '../../types/impact';
import { CollegeLeaderboardItem } from '../../types/analytics';
import { Card } from '../../components/common/Card';
import { Button } from '../../components/common/Button';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { formatCurrency, formatWeightKg } from '../../utils/formatters';

export const ImpactPage: React.FC = () => {
  const { user, role, activeCollegeFilter } = useAuth();
  const { success } = useToast();
  const [impact, setImpact] = useState<EnvironmentalImpactSummary | null>(null);
  const [departments, setDepartments] = useState<ImpactByDepartment[]>([]);
  const [leaderboard, setLeaderboard] = useState<CollegeLeaderboardItem[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const loadImpactData = async () => {
      setIsLoading(true);
      try {
        const filterId = role === 'COLLEGE_ADMIN' ? user?.collegeId : activeCollegeFilter;
        const [impRes, deptRes, leadRes] = await Promise.all([
          impactService.getImpactSummary(filterId),
          impactService.getImpactByDepartment(filterId),
          analyticsService.getCollegeLeaderboard(),
        ]);
        setImpact(impRes);
        setDepartments(deptRes);
        setLeaderboard(leadRes);
      } catch (err) {
        console.error('Impact load failed', err);
      } finally {
        setIsLoading(false);
      }
    };

    loadImpactData();
  }, [role, user?.collegeId, activeCollegeFilter]);

  const handleDownloadCertificate = () => {
    success(
      'Sustainability Certificate Generated',
      'CampusLoop Verified Green Campus ESG report dispatched to your email.'
    );
  };

  if (isLoading || !impact) {
    return <LoadingSpinner size="lg" label="Compiling circular impact ledger..." />;
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-emerald-100 text-emerald-800 text-xs font-semibold mb-2">
            <Sparkles className="w-3.5 h-3.5" />
            <span>CampusLoop ESG & Ecological Ledger</span>
          </div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">
            Sustainability & Circular Impact
          </h1>
          <p className="text-sm text-slate-500 mt-0.5">
            Verified environmental emissions prevented and student financial savings generated by circular resource sharing.
          </p>
        </div>

        <Button
          onClick={handleDownloadCertificate}
          variant="primary"
          icon={<Download className="w-4 h-4" />}
        >
          Download Campus ESG Certificate
        </Button>
      </div>

      {/* Hero Impact Banner */}
      <div className="bg-gradient-to-br from-emerald-900 via-teal-950 to-slate-950 rounded-3xl p-6 sm:p-8 text-white shadow-elevated relative overflow-hidden">
        <div className="relative z-10 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          <div className="space-y-1">
            <div className="flex items-center gap-2 text-emerald-300 text-xs font-semibold uppercase tracking-wider">
              <Leaf className="w-4 h-4" />
              <span>CO₂ Emissions Prevented</span>
            </div>
            <h2 className="text-3xl sm:text-4xl font-black text-white">
              {formatWeightKg(impact.totalKgCo2Saved)}
            </h2>
            <p className="text-xs text-emerald-200/80">
              Equivalent to planting ~{impact.equivalentTreesPlanted} mature trees
            </p>
          </div>

          <div className="space-y-1">
            <div className="flex items-center gap-2 text-teal-300 text-xs font-semibold uppercase tracking-wider">
              <Trash2 className="w-4 h-4" />
              <span>Landfill Waste Diverted</span>
            </div>
            <h2 className="text-3xl sm:text-4xl font-black text-white">
              {formatWeightKg(impact.totalKgWasteDiverted)}
            </h2>
            <p className="text-xs text-teal-200/80">
              Dorm electronics, bicycles, and bound paper recycled
            </p>
          </div>

          <div className="space-y-1">
            <div className="flex items-center gap-2 text-sky-300 text-xs font-semibold uppercase tracking-wider">
              <Droplets className="w-4 h-4" />
              <span>Water Conserved</span>
            </div>
            <h2 className="text-3xl sm:text-4xl font-black text-white">
              {(impact.waterSavedLiters / 1000).toFixed(0)}k Liters
            </h2>
            <p className="text-xs text-sky-200/80">
              Virgin paper and fabric manufacturing offset
            </p>
          </div>

          <div className="space-y-1">
            <div className="flex items-center gap-2 text-amber-300 text-xs font-semibold uppercase tracking-wider">
              <DollarSign className="w-4 h-4" />
              <span>Student Wallet Savings</span>
            </div>
            <h2 className="text-3xl sm:text-4xl font-black text-white">
              {formatCurrency(impact.totalINRStudentSavings)}
            </h2>
            <p className="text-xs text-amber-200/80">
              Direct educational expense burden reduced
            </p>
          </div>
        </div>
      </div>

      {/* Impact by Academic Department */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card
          title="Circular Adoption by Academic Department"
          subtitle="Top contributing faculties in resource circulation"
        >
          <div className="space-y-4">
            {departments.map((dept) => (
              <div key={dept.department} className="space-y-1.5 p-3 rounded-xl bg-slate-50 border border-slate-100">
                <div className="flex items-center justify-between text-xs">
                  <span className="font-bold text-slate-800">{dept.department}</span>
                  <span className="font-semibold text-emerald-700">
                    {dept.co2SavedKg} kg CO₂ &bull; {dept.wasteDivertedKg} kg Waste
                  </span>
                </div>
                <div className="h-2 w-full bg-slate-200 rounded-full overflow-hidden">
                  <div
                    style={{ width: `${Math.min(100, (dept.itemsShared / 800) * 100)}%` }}
                    className="h-full bg-emerald-500 rounded-full"
                  />
                </div>
                <div className="text-[11px] text-slate-500">
                  {dept.itemsShared} textbooks, toolkits, and components shared
                </div>
              </div>
            ))}
          </div>
        </Card>

        {/* Inter-Campus Ranking */}
        <Card
          title="Inter-Campus Circularity Rankings"
          subtitle="Annual sustainability benchmarking"
        >
          <div className="space-y-3">
            {leaderboard.map((item) => (
              <div
                key={item.collegeId}
                className="flex items-center justify-between p-3 rounded-xl border border-slate-200/80 bg-white hover:border-primary-300 transition-colors"
              >
                <div className="flex items-center gap-3">
                  <div
                    className={`w-7 h-7 rounded-lg flex items-center justify-center font-bold text-xs ${
                      item.rank === 1
                        ? 'bg-amber-100 text-amber-900 border border-amber-300'
                        : item.rank === 2
                        ? 'bg-slate-200 text-slate-800 border border-slate-300'
                        : 'bg-emerald-100 text-emerald-900 border border-emerald-300'
                    }`}
                  >
                    #{item.rank}
                  </div>
                  <div>
                    <h4 className="text-xs font-bold text-slate-900">{item.collegeName}</h4>
                    <p className="text-[11px] text-slate-500">
                      {item.exchangesCount} exchanges &bull; {formatCurrency(item.studentSavingsINR)} saved
                    </p>
                  </div>
                </div>

                <div className="text-right">
                  <span className="text-xs font-extrabold text-emerald-600 block">
                    {item.co2SavedKg} kg CO₂
                  </span>
                  <span className="text-[10px] text-slate-400">prevented</span>
                </div>
              </div>
            ))}
          </div>
        </Card>
      </div>
    </div>
  );
};
